[package]
name = "chatty_audio"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
axum = { version = "0.8.6" }
des = { version = "0.7.0" }
block-modes = { version = "0.8.1" }
base64 = { version = "0.22.1" }
